namespace bitcraze.crazyflielib
{
    [default_interface]
    runtimeclass Crazyflie
    {
        //
        // Summary:
        //      Creates an instance of a Crazyflie with the given deviceId.
        //      Device ID can be retrieved with ScanInterfacesAsync.
        Crazyflie(String deviceId);

        //
        // Summary:
        //      Initiates connection to the Crazyflie asynchronously.
        Windows.Foundation.IAsyncAction
        ConnectAsync();

        //
        // Summary:
        //      Sends a legacy RPYT setpoint to the Crazyflie.
        Windows.Foundation.IAsyncOperation<Boolean>
        SendCommanderPacketAsync(
            Single roll,
            Single pitch,
            Single yaw,
            Single thrust);

        //
        // Summary:
        //      Sends a hover setpoint to the Crazyflie.
        Windows.Foundation.IAsyncOperation<Boolean>
        SendCommanderHoverPacketAsync(
            Single vx,
            Single vy,
            Single yawrate,
            Single zdist);

        //
        // Summary:
        //      Sends a stop setpoint to the Crazyflie.
        Windows.Foundation.IAsyncOperation<Boolean>
        SendCommanderStopPacketAsync();

        //
        // Summary:
        //      Asynchronously searches for Crazyflie devices across all
        //      available interfaces.
        static Windows.Foundation.IAsyncOperation<
            Windows.Foundation.Collections.IVector<String> >
            ScanInterfacesAsync();
    }
}
